### PR TITLE
Adding bigText support (expanded notification) && improving notification press event

### PR DESCRIPTION
**Pull request by julianocomg**
:beers:

### CODE REVIEW

**Comment by CentaurWarchief** [comment]
:+1:

**Comment by Neson** [comment]
Thanks very much! And sorry for the delay since I've been busy around Chinese New Year.

Only one question: why do we need to add `sendBroadcast ` on https://github.com/Neson/react-native-system-notification/pull/14/files#diff-237cc59d2764ba779d3ace196a412e44R46? I think that broadcast will not be caught by the app because the app hasn't been fully started right after the execution of`context.startActivity(launchIntent);`. Currently I've used `launchIntent.putExtra` ([here](https://github.com/Neson/react-native-system-notification/pull/14/files#diff-237cc59d2764ba779d3ace196a412e44R41)) to pass that data while launching the app, pass it into JS through the Java native module [here](https://github.com/Neson/react-native-system-notification/blob/master/android/src/main/java/io/neson/react-native/notification/NotificationModule.java#L248-L260) and check it in JS [here](https://github.com/Neson/react-native-system-notification/blob/master/index.js#L73). So I think it's necessary to add these lines. Are there any considerations that I've ignored?

**Comment by julianocomg** [comment]
Hi, and happy new year :monkey: 

So... The module works fine when the app is launching, BUT, the callback wasn't firing when coming from background to foreground. If the app is open in background, and the notification is pressed, the app come to foreground, but without callback :/

**Comment by Neson** [comment]
Oh I see. The last doubt is that will the callback be fired multiple times in some cases? But since this is a small issue and might not probably happen (if the app is not running, it won't be able to catch the broadcast in time, or if the app is running in background, the callback won't be fired), I'm merging this first. :smile:

**Comment by julianocomg** [comment]
In my tests this broadcast is sent only when the app is already running in background (https://github.com/Neson/react-native-system-notification/blob/master/android/src/main/java/io/neson/react-native/notification/NotificationEventReceiver.java#L46)

So I think everything will work as expected now :+1:

**Pull request merged**
