### PR TITLE
Added remove all listeners function

### PR DESCRIPTION
**Pull request by lukefanning**
Added a removeAllListeners() func so we can properly clean up in componentWillUnmount()

### CODE REVIEW

**Comment by Neson** [comment]
Looks good! But since this project has no automatic tests, are you sure that the functionality is working as expected?

In addition, it will be nice if you can add some introductions for this function in README.md by the way, probably in the [handle-notification-click-event](https://github.com/Neson/react-native-system-notification#handle-notification-click-event) section.

**Comment by lukefanning** [comment]
I've not had any issues using this function while using your module alongside react-native-gcm-android. I have generated notifications while the app is in the background, from the app being closed/killed and while the app is in the foreground ok.

**Comment by fender** [comment]
@lukefanning Great, I need this too. @Neson can we merge and have a new release? Thanks for the great module!

**Comment by Neson** [comment]
Ok, merged! And thank you for improving the code.

**Pull request merged**
