### PR TITLE
add FCM support, largeImage, multiline remote push notification

### PR DESCRIPTION
**Pull request by sichacvah**

### CODE REVIEW

**Comment by mehcode** [comment]
@Neson Can we get this merged in ?

I additionally had to do https://github.com/mehcode/react-native-system-notification/commit/e601fe823fa3270061534689df403a78785276e6 in order to get it to compile

**Comment by Neson** [comment]
Looks great, thanks!

**Comment by Neson** [comment]
Published in `v0.2.1`.

**Comment by JonesN7** [comment]
Why don't you do a pull request on that @mehcode? Those libraries are new dependencies, correct?

**Pull request merged**
